version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0
    container_name: elastic-0
    environment:
      - node.name=elastic-0
      - cluster.name=test-cluster
      - cluster.initial_master_nodes=elastic-0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms15g -Xmx15g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data00:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana-oss:7.4.0
    environment:
      - SERVER_NAME="kibana"
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - LOGGING_SILENT=true
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic
      
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: minor-g3
    ports:
      - 3306:3306
    volumes: 
      - db00:/usr/lib/mysql
    networks:
      - database
      
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  data00:
    driver: local
  db00:
    driver: local
  portainer_data:
    driver: local

networks:
  elastic:
    driver: bridge
  database:
    driver: bridge
  portainer:
    driver: bridge